name: Download Artifact

on:
  push:
    tags:
      - "2.3.3"
  workflow_dispatch:

jobs:
  download-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Gradle Build
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: "**/build/libs/*.jar"

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
